/**
 * Migration 178: drop preview keys written by the old generator.
 *
 * generatePreviewImage used to keep the SOURCE basename verbatim, extension and
 * all, while always writing JPEG bytes. So a `.webp` upload produced
 * `previews/preview_shot.webp` holding a JPEG, and a `.png` upload produced
 * `preview_logo.png` holding a JPEG.
 *
 * That was harmless while the preview route hard-coded `Content-Type:
 * image/jpeg`. It stopped being harmless the moment the encoding started
 * varying: the route now reads the extension, so a legacy `.webp` key is
 * announced as `image/webp` while containing JPEG — and the response carries
 * `X-Content-Type-Options: nosniff`, so the browser will not quietly correct
 * it. The lightbox shows a broken image for every photo that happened to be
 * uploaded as WebP.
 *
 * The legacy `.png`-keyed previews are wrong in the other direction: they are
 * flattened JPEGs of what may have been a transparent source, which is the
 * defect the new encoder fixes and which `isPreviewValid` would otherwise let
 * stand forever.
 *
 * Clearing the column is the whole repair. Previews are lazily regenerated by
 * ensurePreviewImage on the next open, under the new naming and the new
 * encoder, so the only cost is one regeneration per photo that is actually
 * viewed. Nothing is deleted from storage — a migration is the wrong place to
 * reach into a backend that may be S3 — so the old objects linger as
 * unreferenced bytes, which the storage breakdown counts honestly.
 *
 * Deliberately clears ALL of them, not just the ones whose extension looks
 * suspicious. A `.jpg`-keyed legacy preview is byte-correct, but it may still
 * be a flattened rendition of a transparent or animated source, and there is
 * no way to tell from the key. One lazy regeneration is cheaper than reasoning
 * about which of them lied.
 */

exports.up = async function(knex) {
  if (!(await knex.schema.hasTable('photos'))) return;
  if (!(await knex.schema.hasColumn('photos', 'preview_path'))) return;

  const cleared = await knex('photos')
    .whereNotNull('preview_path')
    .update({ preview_path: null });

  if (cleared) {
    console.log(`178_reset_legacy_preview_paths: cleared ${cleared} preview key(s); they regenerate on next view`);
  }
};

/**
 * Irreversible by design, and harmless: the column held a cache key, and the
 * cache rebuilds itself. There is nothing to restore.
 */
exports.down = async function() {
  console.log('178_reset_legacy_preview_paths: rollback is a no-op (preview keys are a regenerable cache)');
};
